# Generated by Django 6.1.1 on 2026-10-05 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('pinyin_to_en', 'Pinyin to English'), ('en_to_zh', 'English to Chinese'), ('zh_to_en', 'Chinese to English')], max_length=20)),
                ('easy_streak', models.PositiveIntegerField(default=0)),
                ('easy_count', models.PositiveIntegerField(default=0)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.CharField(max_length=64)),
                ('pinyin', models.CharField(max_length=128)),
                ('english_basic', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['chinese'],
            },
        ),
        migrations.CreateModel(
            name='WordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.word')),
            ],
            options={
                'db_table': 'word_category',
            },
        ),
        migrations.AddField(
            model_name='userword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to='api.word'),
        ),
        migrations.AddField(
            model_name='category',
            name='words',
            field=models.ManyToManyField(blank=True, related_name='categories', through='api.WordCategory', to='api.word'),
        ),
        migrations.AddIndex(
            model_name='userword',
            index=models.Index(fields=['user', 'due_on'], name='api_userwor_user_id_eff08b_idx'),
        ),
        migrations.AddConstraint(
            model_name='userword',
            constraint=models.UniqueConstraint(fields=('user', 'word', 'mode'), name='uniq_userword_user_word_mode'),
        ),
        migrations.AddConstraint(
            model_name='wordcategory',
            constraint=models.UniqueConstraint(fields=('word', 'category'), name='uniq_word_category'),
        ),
    ]
