# Generated by Django 6.1.1 on 2026-10-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_vocabulary_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='simplified',
            field=models.CharField(default='', max_length=64),
        ),
    ]
