# Generated by Django 6.1.1 on 2026-10-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_word_simplified'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='hsk_level',
            field=models.IntegerField(default=0),
        ),
    ]
