"""Shared cross-level study categories for HSK vocabulary cards."""

STUDY_CATEGORIES: list[str] = [
    "Greetings & Social Expressions",
    "People, Family & Relationships",
    "Home & Household",
    "Food, Cooking & Dining",
    "Shopping & Consumer Life",
    "Money, Banking & Finance",
    "Numbers, Time & Measurement",
    "Places, Directions & Geography",
    "Travel & Transportation",
    "School, Learning & Language",
    "Work, Careers & Business",
    "Medical Chinese",
    "Emotions & Mental States",
    "Personality, Behavior & Values",
    "Communication, Conversation & Writing",
    "Actions & Daily Routines",
    "Movement & Physical Actions",
    "Descriptions, Qualities & Comparisons",
    "Nature, Animals & Plants",
    "Weather, Climate & Environment",
    "Society, Culture & Customs",
    "Government, Politics & Public Affairs",
    "Law, Crime & Justice",
    "Science & Technology",
    "Media, Internet & Information",
    "Arts, Literature & Entertainment",
    "Sports & Competition",
    "Abstract Ideas & Reasoning",
    "Cause, Effect & Conditions",
    "Change, Development & Processes",
    "Conflict, Success & Failure",
    "Rules, Duties & Permissions",
    "Idioms & Fixed Expressions",
    "Grammar & Function Words",
    "Materials, Construction & Industry",
]
