"""Suggested primary study categories for HSK cards, keyed by level."""

HSK_CATEGORIES: dict[int, list[str]] = {
    1: [
        "Greetings & Introductions - HSK 1",
        "People & Family - HSK 1",
        "Numbers, Time & Quantity - HSK 1",
        "Daily Life, Food & Places - HSK 1",
    ],
    2: [
        "Conversation & Social Expressions - HSK 2",
        "Daily Routines, Home & People - HSK 2",
        "Travel, Directions & Transport - HSK 2",
    ],
    3: [
        "Communication & Relationships - HSK 3",
        "Home, Food & Daily Life - HSK 3",
        "School, Learning & Work - HSK 3",
        "Travel, Places & Geography - HSK 3",
        "Nature, Weather & Animals - HSK 3",
        "Health, Body & Descriptions - HSK 3",
    ],
    4: [
        "Conversation, Opinions & Emotions - HSK 4",
        "People, Family & Relationships - HSK 4",
        "Work, Business & Administration - HSK 4",
        "School, Learning & Exams - HSK 4",
        "Home, Food & Shopping - HSK 4",
        "Travel, Transport & Directions - HSK 4",
        "Health, Body & Care - HSK 4",
        "Time, Plans & Scheduling - HSK 4",
        "Nature, Weather & Environment - HSK 4",
        "Society, Culture & Government - HSK 4",
        "Actions, Change & Descriptions - HSK 4",
    ],
    5: [
        "Conversation, Argument & Expression - HSK 5",
        "Emotions, Personality & Relationships - HSK 5",
        "Work, Careers & Business - HSK 5",
        "Education, Learning & Knowledge - HSK 5",
        "Health, Body & Medicine - HSK 5",
        "Home, Food & Daily Routines - HSK 5",
        "Shopping, Money & Consumption - HSK 5",
        "Travel, Transport & Places - HSK 5",
        "Society, Culture & Government - HSK 5",
        "Nature, Weather & Environment - HSK 5",
        "Technology, Media & Information - HSK 5",
        "Time, Change & Development - HSK 5",
        "Actions, Movement & Interaction - HSK 5",
        "Descriptions, Qualities & Comparisons - HSK 5",
        "Arts, Entertainment & Hobbies - HSK 5",
        "Reasoning, Decisions & Problem Solving - HSK 5",
    ],
    6: [
        "Communication, Language & Ideas - HSK 6",
        "Work, Business & Finance - HSK 6",
        "Society, Government & Law - HSK 6",
        "Health, Medicine & the Body - HSK 6",
        "Nature, Science & Geography - HSK 6",
        "People, Emotions & Relationships - HSK 6",
        "Daily Life, Travel & Culture - HSK 6",
    ],
}
